version: AppVeyor build {build}
image: Ubuntu
init:
- sh: >-
    mkdir ../resources
    
    mkdir ../libnx
    
    wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -P ../resources
install:
- sh: >-
    sudo dpkg -i ../resources/devkitpro-pacman.deb
    
    echo -en "\n\n" | sudo dkp-pacman -S switch-dev
    
    echo -en "\n\n" | sudo dkp-pacman -S devkitARM
    
    source /etc/profile.d/devkit-env.sh
    
    git submodule update --init --recursive
build_script:
- sh: >-
    make
    
    COMMIT_ID="$(git rev-parse HEAD)"
    
    RELEASE_FILE="../powertoolsnx/bin-PowerToolsNX-${COMMIT_ID}.zip"
    
    RELEASE_FOLDER="../bin-PowerToolsNX-${COMMIT_ID}"
    
    mkdir ${RELEASE_FOLDER}
    
    find . -name '*.nro' | cpio -pdm ${RELEASE_FOLDER}
    
    find . -name '*.nso' | cpio -pdm ${RELEASE_FOLDER}
    
    find . -name '*.nacp' | cpio -pdm ${RELEASE_FOLDER}
    
    find . -name '*.elf' | cpio -pdm ${RELEASE_FOLDER}
    
    find . -name '*.pfs0' | cpio -pdm ${RELEASE_FOLDER}
    
    TEMP="$(realpath ${RELEASE_FOLDER})"
    
    cd ${RELEASE_FOLDER
    }
    zip -9 -r ${RELEASE_FILE} *
    
    cd ${APPVEYOR_BUILD_FOLDER}
    
    make dist
artifacts:
- path: bin-PowerToolsNX-*.zip
- path: out/*.zip
